### ISSUE TITLE
Set Project/Activity/Description on widget

### ISSUE THREAD

**Issue by Sim0nW0lf** [infeeeee/kimai2-cmd-rainmeter#3]
Hi, I was wondering if it was possible to implement that an Project/Activity/Description can be selected on the widget aswell?
Otherwise the cmd windows always has to be launched and for some people that is really confusing.

Thanks for your work on this!

**Comment by infeeeee** [comment]
It uses the latest activities from your kimai server, so you can also set it up on the webui as well. 

Implementing an activity selector shouldn't be a big deal, but adding a description box sounds a big task. The whole UX should be rethinked as well, I wanted to use this as a single button widgets, so I can change between tasks with 2 clicks.

I don't use kimai nowadays, and I'm busy with other projects, so I won't implement it unfortunately. But if you can write it, I would be happy to accept your pull request, and help in it. 

Also check out Kemai, it's a much more full featured client: https://github.com/alexandreptj/kemai

**Comment by Sim0nW0lf** [comment]
Thanks for your detailed answer! 👍🏼
